### ISSUE TITLE
https for website

### ISSUE THREAD

**Issue by dirkschumacher** [reconhub/reconhub.github.io#3]
Is there any way to add https to github pages with a custom domain?

**Comment by thibautjombart** [comment]
Do you mean for your section in the people page? Shouldn't be a problem.
Which url would you like to use?

**Comment by dirkschumacher** [comment]
I would like to see http://www.repidemicsconsortium.org => http**s**://www.repidemicsconsortium.org

**Comment by thibautjombart** [comment]
Got you. Just enquired about it to the domain name provider.

**Comment by thibautjombart** [comment]
Checked: it seems this will not be possible. github does not currently allow https with custom domain names.
